[project]
name = "playground"
version = "0.1.0"
description = "This is a playground project or sandboxing project to run experiments"
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.91",
    "openai>=1.84.0",
]
